language: nix
matrix:
  include:
  - name: 'Run with updates'
    env: UPDATE_CHANNEL=true
  - name: 'Run without channel updates'
script:
  - df -h
  - if [ -n "$UPDATE_CHANNELS" ]; then; make update; fi
  - make
