pkgs: with pkgs; [
  qt510.albert
  alsaUtils # for amixer
  pavucontrol
  arc-theme
  feh
  fontconfig-ultimate
  gksu
  gnome2.gnome_icon_theme
  gnome3.adwaita-icon-theme
  gnome3.file-roller
  gtk-engine-murrine
  gtk_engines
  gvfs
  i3-wk-switch
  i3lock-color
  kdeFrameworks.networkmanager-qt
  networkmanagerapplet
  notify-desktop
  numix-cursor-theme
  compton
  playerctl
  redshift
  screenkey
  shutter
  xdotool
  xfce.xfce4notifyd
  xfce.xfce4settings
  xfce.xfce4volumed
  xorg.xbacklight
  xorg.xrefresh
  xss-lock
  rofi
  xclip
  wmfocus
]
